sonar.projectKey=ribarski_prova03-integration-test-EduardoRibarski
sonar.organization=ribarski
sonar.projectName=Playwright E2E
sonar.projectVersion=1.0
sonar.sources=./src
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info